-- Customers master with a 512-dim identity embedding
CREATE TABLE customers (
  customer_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name       VARCHAR2(200),
  dob             DATE,
  phone_e164      VARCHAR2(20),
  email_norm      VARCHAR2(254),
  gov_id_norm     VARCHAR2(64),      -- PAN/Aadhaar (normalized)
  addr_line       VARCHAR2(400),
  city            VARCHAR2(120),
  state           VARCHAR2(120),
  postal_code     VARCHAR2(20),
  country         VARCHAR2(2),
  identity_text   CLOB,               -- canonical text we embedded
  identity_vec    VECTOR(512, FLOAT32, DENSE),
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Optional: separate table to store portraits/face embeddings if you use them
CREATE TABLE customer_faces (
  face_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id     NUMBER REFERENCES customers(customer_id) ON DELETE CASCADE,
  face_vec        VECTOR(512, FLOAT32, DENSE),
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Workaround table to bind a single query vector safely (array('f', ...))
-- You insert one row with your query vector, self-join, then delete.
CREATE TABLE query_identity (
  qid             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  qvec            VECTOR(512, FLOAT32, DENSE),
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP
);
